// Metadata sidecar persisted next to every generated app, plus the
// `composoft inspect` views that read those sidecars to surface
// workspace-wide rollups (which gaps got flagged, which customers asked
// for similar things, what's in any one customer's app).
//
// The CLI in cli.ts writes the meta at end-of-compose and routes the
// `inspect` subcommand into the formatters here. The helpers are pure
// (data-in / string-out) so the tests in _test.ts can drive them
// against tmpdir fixtures without spawning a process.

import { readdir, readFile, stat } from "node:fs/promises";
import { basename, join } from "node:path";

/**
 * Schema for the JSON written to `<out>/.composoft-meta.json` after every
 * successful compose run. Travels with the generated app's git history,
 * surfaces in PR reviews, and feeds the inspect views below. Stable shape
 * — adding fields is fine, removing or renaming requires a new alpha.
 */
export type ComposoftMeta = {
  customer: string;
  briefPath: string;
  briefContent: string;
  modelNotes: string[];
  pages: Array<{
    path: string;
    blockCount: number;
  }>;
  registry: {
    name: string;
    version: string;
  };
  composerVersion: string;
  runtimeVersion: string;
  generatedAt: string;
  filesWritten: number;
};

export type LoadedMeta = {
  /** Directory containing the meta file — `<workspace>/apps/<customer>/`. */
  dir: string;
  /** Parsed sidecar payload. */
  meta: ComposoftMeta;
};

/**
 * Walk every `<rootDir>/apps/<customer>/.composoft-meta.json` and return every meta we
 * could parse. Directories without the sidecar are silently skipped — the
 * CLI inspect command may run in a workspace with a mix of pre-meta apps
 * (generated by older composer versions) and current ones; we surface
 * what's available.
 *
 * Bad JSON is logged to stderr and skipped — better to show partial
 * results than fail the whole inspect run on one corrupt sidecar.
 */
export async function loadMetas(rootDir: string): Promise<LoadedMeta[]> {
  const appsDir = join(rootDir, "apps");
  let entries: string[];
  try {
    entries = await readdir(appsDir);
  } catch (e) {
    if ((e as NodeJS.ErrnoException).code === "ENOENT") return [];
    throw e;
  }

  const out: LoadedMeta[] = [];
  for (const entry of entries) {
    const appDir = join(appsDir, entry);
    let s: Awaited<ReturnType<typeof stat>>;
    try {
      s = await stat(appDir);
    } catch {
      continue;
    }
    if (!s.isDirectory()) continue;
    const metaPath = join(appDir, ".composoft-meta.json");
    let raw: string;
    try {
      raw = await readFile(metaPath, "utf8");
    } catch (e) {
      // No sidecar in this app dir — skip silently. Pre-meta apps from
      // older composer versions land here and we don't want to spam.
      if ((e as NodeJS.ErrnoException).code === "ENOENT") continue;
      console.error(`[composoft inspect] could not read ${metaPath}: ${(e as Error).message}`);
      continue;
    }
    let parsed: ComposoftMeta;
    try {
      parsed = JSON.parse(raw) as ComposoftMeta;
    } catch (e) {
      console.error(`[composoft inspect] ${metaPath} is not valid JSON: ${(e as Error).message}`);
      continue;
    }
    if (!isValidMeta(parsed)) {
      console.error(`[composoft inspect] ${metaPath} is missing required fields; skipped`);
      continue;
    }
    out.push({ dir: appDir, meta: parsed });
  }
  // Newest first — what an FDE wants to see at the top of a daily review.
  out.sort(
    (a, b) =>
      new Date(b.meta.generatedAt).getTime() -
      new Date(a.meta.generatedAt).getTime(),
  );
  return out;
}

/**
 * Cheap shape check. We don't validate every nested field — the schema
 * is internal and bumps via alpha versions. The check here just guards
 * the inspect formatters from crashing on a malformed sidecar.
 */
export function isValidMeta(value: unknown): value is ComposoftMeta {
  if (typeof value !== "object" || value === null) return false;
  const v = value as Record<string, unknown>;
  return (
    typeof v.customer === "string" &&
    typeof v.briefPath === "string" &&
    typeof v.briefContent === "string" &&
    Array.isArray(v.modelNotes) &&
    Array.isArray(v.pages) &&
    typeof v.registry === "object" &&
    v.registry !== null &&
    typeof v.composerVersion === "string" &&
    typeof v.runtimeVersion === "string" &&
    typeof v.generatedAt === "string" &&
    typeof v.filesWritten === "number"
  );
}

// --- Formatters ------------------------------------------------------------

/**
 * Default `composoft inspect` view: one row per generated app, columns
 * for customer / brief / pages / blocks / notes / generated date.
 *
 * Manual padding — table width is small and a third-party formatter
 * isn't worth the dep.
 */
export function formatTable(metas: LoadedMeta[]): string {
  if (metas.length === 0) {
    return "No composoft apps found in ./apps/. Run `composoft compose` first.";
  }
  const headers = ["CUSTOMER", "BRIEF", "PAGES", "BLOCKS", "NOTES", "GENERATED"];
  const rows = metas.map(({ meta }) => {
    const blocks = meta.pages.reduce((acc, p) => acc + p.blockCount, 0);
    const date = (meta.generatedAt.split("T")[0] ?? meta.generatedAt).slice(0, 10);
    return [
      meta.customer,
      basename(meta.briefPath),
      String(meta.pages.length),
      String(blocks),
      String(meta.modelNotes.length),
      date,
    ];
  });
  // Compute per-column widths.
  const widths = headers.map((h, i) =>
    Math.max(h.length, ...rows.map((r) => (r[i] ?? "").length)),
  );
  const renderRow = (row: string[]) =>
    row.map((cell, i) => cell.padEnd(widths[i] ?? cell.length)).join("  ").trimEnd();
  return [renderRow(headers), ...rows.map(renderRow)].join("\n");
}

/**
 * `composoft inspect --gaps`: aggregate every model note across every
 * customer's metadata. Group by exact-match string. Sort by frequency
 * descending — answers "which gap blocks the most customers" at a
 * glance.
 *
 * Exact-match grouping is intentional: model notes are free-form
 * sentences, and trying to fuzzy-match would surface false alignments.
 * If two notes describe the same gap with different wording, the FDE
 * sees them as separate rows — same total count, different surface.
 * That's a feature; it shows the FDE which language is dominant.
 */
export function aggregateGaps(metas: LoadedMeta[]): {
  totalCustomers: number;
  byNote: Array<{ note: string; count: number; customers: string[] }>;
} {
  const byNote = new Map<string, Set<string>>();
  for (const { meta } of metas) {
    for (const note of meta.modelNotes) {
      let set = byNote.get(note);
      if (!set) {
        set = new Set<string>();
        byNote.set(note, set);
      }
      set.add(meta.customer);
    }
  }
  const rows = Array.from(byNote.entries())
    .map(([note, customers]) => ({
      note,
      count: customers.size,
      customers: Array.from(customers).sort(),
    }))
    .sort((a, b) => {
      if (b.count !== a.count) return b.count - a.count;
      return a.note.localeCompare(b.note);
    });
  return { totalCustomers: metas.length, byNote: rows };
}

export function formatGaps(metas: LoadedMeta[]): string {
  const { totalCustomers, byNote } = aggregateGaps(metas);
  if (totalCustomers === 0) {
    return "No composoft apps found in ./apps/. Run `composoft compose` first.";
  }
  if (byNote.length === 0) {
    return `GAPS FLAGGED ACROSS ${totalCustomers} CUSTOMER${totalCustomers === 1 ? "" : "S"}\n\nNone — every brief was satisfied without notes.`;
  }
  const lines: string[] = [
    `GAPS FLAGGED ACROSS ${totalCustomers} CUSTOMER${totalCustomers === 1 ? "" : "S"}`,
    "",
  ];
  for (const row of byNote) {
    lines.push(`${row.count}x  ${row.note}`);
    lines.push(`     Asked in: ${row.customers.join(", ")}`);
    lines.push("");
  }
  return lines.join("\n").trimEnd();
}

/**
 * `composoft inspect <customer>`: pretty-print one customer's full
 * metadata. Case-insensitive match on `meta.customer`. If no match,
 * the caller surfaces the available list so the FDE can correct a typo
 * without rerunning.
 */
export function findCustomer(
  metas: LoadedMeta[],
  needle: string,
): LoadedMeta | null {
  const target = needle.trim().toLowerCase();
  return metas.find((m) => m.meta.customer.trim().toLowerCase() === target) ?? null;
}

export function formatCustomerDetail(loaded: LoadedMeta): string {
  const m = loaded.meta;
  const blocks = m.pages.reduce((a, p) => a + p.blockCount, 0);
  const pageWidth = m.pages.reduce((w, p) => Math.max(w, p.path.length), 0);
  const lines: string[] = [];
  lines.push(`Customer:        ${m.customer}`);
  lines.push(`Brief:           ${basename(m.briefPath)}`);
  lines.push(`Generated:       ${m.generatedAt}`);
  lines.push(`Registry:        ${m.registry.name}@${m.registry.version}`);
  lines.push(`Composer:        ${m.composerVersion}`);
  lines.push(`Runtime:         ${m.runtimeVersion}`);
  lines.push(`Files written:   ${m.filesWritten}`);
  lines.push("");
  lines.push(`Pages (${m.pages.length}):`);
  for (const p of m.pages) {
    lines.push(`  ${p.path.padEnd(pageWidth)}   ${p.blockCount} block${p.blockCount === 1 ? "" : "s"}`);
  }
  lines.push("");
  lines.push(`Model notes (${m.modelNotes.length}):`);
  if (m.modelNotes.length === 0) {
    lines.push("  (none)");
  } else {
    m.modelNotes.forEach((note, i) => {
      lines.push(`  ${i + 1}. ${note}`);
    });
  }
  lines.push("");
  lines.push(`Total blocks: ${blocks}`);
  lines.push("");
  lines.push("Brief:");
  lines.push("-----");
  // Indent every line so the brief reads as a quoted block, not a wall
  // of unmarked text running off the bottom of the inspect view.
  for (const line of m.briefContent.split(/\r?\n/)) {
    lines.push(`  ${line}`);
  }
  return lines.join("\n").trimEnd();
}

export function formatCustomerNotFound(needle: string, metas: LoadedMeta[]): string {
  const available = metas.map((m) => m.meta.customer).join(", ");
  const fallback = "(none — run 'composoft compose' first)";
  return `No app found for "${needle}". Available: ${available || fallback}`;
}
